server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: event-ticket-booking
  
  datasource:
    url: jdbc:mysql://localhost:3306/event_booking_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  
  mail:
    host: smtp.gmail.com
    port: 587
    username: your-email@gmail.com
    password: your-app-password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# JWT Configuration
jwt:
  secret: mySecretKey123456789012345678901234567890
  expiration: 86400000 # 24 hours

# Stripe Configuration
stripe:
  api:
    key: sk_test_your_stripe_secret_key

# File Upload Configuration
file:
  upload-dir: ./uploads/tickets

logging:
  level:
    com.eventbooking: DEBUG
    org.springframework.security: DEBUG